version: '3'
networks:
  geo-quizz.net:
    driver: bridge
services:

  api.geo-quizz:
    image: 'canals/php:8.2'
    env_file: ./quiz.env
    ports:
      - '11111:80'
    volumes:
      - ../quiz.geoquizz:/var/www
      - ../quiz.geoquizz/public:/var/www/html
    working_dir: /var/www/
    networks:
      - geo-quizz.net
    depends_on:
      geo.quizz.db:
        condition: service_started

  geo.quizz.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./quiz.env
    ports:
      - '11112:3306'
    networks:
      - geo-quizz.net
    volumes:
      - ../quiz.geoquizz/sql:/var/sql

  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '11113:8080'
    networks:
      - geo-quizz.net

  api.geo-auth:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '11114:80'
    volumes:
      - ../auth.geoquizz:/var/www
      - ../auth.geoquizz/public:/var/www/html
    working_dir: /var/www
    networks:
      - geo-quizz.net
    depends_on:
      - geo.auth.db

  geo.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '11115:3306'
    networks:
      - geo-quizz.net
    volumes:
      - ../auth.geoquizz/sql:/var/sql

  httpd:
    image: nginx:latest
    volumes:
      - ../../frontend-geoquizz/dist:/usr/share/nginx/html
    ports:
      - "11116:80"