version: '3'
networks:
  geo-quizz.net:
    driver: bridge
services:

  api.geo-quizz:
    image: 'canals/php:8.2'
    env_file: ./quiz.env
    ports:
      - '2080:80'
    volumes:
      - ../quiz.geoquizz:/var/www
      - ../quiz.geoquizz/public:/var/www/html
    working_dir: /var/www/
    networks:
      - geo-quizz.net
    depends_on:
      geo.quizz.db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  geo.quizz.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./quiz.env
    ports:
      - '3307:3306'
    networks:
      - geo-quizz.net
    volumes:
      - ../quiz.geoquizz/sql:/var/sql

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - geo-quizz.net

  api.geo-auth:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '2780:80'
    volumes:
      - ../auth.geoquizz:/var/www
      - ../auth.geoquizz/public:/var/www/html
    working_dir: /var/www
    networks:
      - geo-quizz.net
    depends_on:
      - geo.auth.db

  geo.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '3308:3306'
    networks:
      - geo-quizz.net
    volumes:
      - ../auth.geoquizz/sql:/var/sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 8s
      timeout: 30s
      retries: 3
    networks:
      - geo-quizz.net
    volumes:
      - ../rabbitmq.geoquizz:/var/lib/rabbitmq
    env_file: ./rab.env